apiVersion: cloudresources.appvia.io/v2beta2
kind: CloudResourcePlan
metadata:
  name: azure-network-build
spec:
  scope:
    allStages: true
    allWorkspaces: true
  cloud: azure
  description: blank
  inputs:
  - description: blank
    name: resource_group_name
    type: string
  - description: blank
    name: location
    type: string
  terraform:
    moduleURL: https://github.com/appvia/terraform-azurerm-wayfinder-provisioning//network/build
    moduleVersion: azure-network-build
    tfVarsTemplate: |
      resource_group_name = "{{ .Inputs.resource_group_name }}"
      location = "{{ .Inputs.location }}"
  version: 0.0.1